Repository cloudradar-monitoring/frontman, pull requests merged in 2018-11, with the labels that each got.

#9 Mark as pre-realease when a rc tag is present
  .circleci/config.yml
Labels: enhancement

#8 Fix msi filename
  .circleci/config.yml
Labels: bug, enhancement

#11 set default log level to error and warn user if invalid log level is set
  cmd/frontman/main.go
  config.go
Labels: enhancement

#13 initialise the map before using it
  handler.go
Labels: bug

#12 remove additional call to fm.SetLogLevel
  config.go
  log.go
Labels: bug

#17 return empty but initialised map instead nil
  handler.go
  types.go
Labels: bug

#14 refactoring: split up and simplify runTCPCheck
  tcp.go
Labels: codestyle

#20 refactor webcheck
  types.go
  webcheck.go
Labels: codestyle

#25 Add .gitignore
  .gitignore
Labels: enhancement

#26 rework generation of default config
  Gopkg.lock
  Gopkg.toml
  cmd/frontman/main.go
  config.go
  vendor/github.com/BurntSushi/toml/COPYING
  vendor/github.com/BurntSushi/toml/cmd/toml-test-decoder/COPYING
  vendor/github.com/BurntSushi/toml/cmd/toml-test-encoder/COPYING
  vendor/github.com/BurntSushi/toml/cmd/tomlv/COPYING
  vendor/github.com/troian/toml/.gitignore
  vendor/github.com/troian/toml/.travis.yml
  vendor/github.com/troian/toml/COMPATIBLE
  vendor/github.com/troian/toml/COPYING
  vendor/github.com/troian/toml/Makefile
  vendor/github.com/troian/toml/README.md
  vendor/github.com/troian/toml/cmd/toml-test-decoder/COPYING
  vendor/github.com/troian/toml/cmd/toml-test-encoder/COPYING
  vendor/github.com/troian/toml/cmd/tomlv/COPYING
  vendor/github.com/troian/toml/decode.go
  vendor/github.com/troian/toml/decode_meta.go
  vendor/github.com/troian/toml/doc.go
  vendor/github.com/troian/toml/encode.go
  vendor/github.com/troian/toml/encoding_types.go
  vendor/github.com/troian/toml/encoding_types_1.1.go
  vendor/github.com/troian/toml/lex.go
  vendor/github.com/troian/toml/parse.go
  vendor/github.com/troian/toml/session.vim
  vendor/github.com/troian/toml/type_check.go
  vendor/github.com/troian/toml/type_fields.go
Labels: enhancement

#24 remove SetVersion and pass version as argument to New
  cmd/frontman/main.go
  config.go
Labels: codestyle
