Repository cloudradar-monitoring/frontman, pull requests merged in 2018-12, with the labels that each got.

#28 refactor main.go
  cmd/frontman/main.go
  config.go
  handler.go
Labels: codestyle

#29 Separate configuration and functionality
  cmd/frontman/main.go
  config.go
  frontman.go
  handler.go
  log.go
  ping.go
  ssl.go
  tcp.go
  webcheck.go
Labels: enhancement

#32 adjust to new signing system
  .circleci/config.yml
  build-win.bat
Labels: enhancement

#31 add test for config handling
  Gopkg.lock
  Gopkg.toml
  config_test.go
  vendor/github.com/davecgh/go-spew/LICENSE
  vendor/github.com/davecgh/go-spew/spew/bypass.go
  vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  vendor/github.com/davecgh/go-spew/spew/common.go
  vendor/github.com/davecgh/go-spew/spew/config.go
  vendor/github.com/davecgh/go-spew/spew/doc.go
  vendor/github.com/davecgh/go-spew/spew/dump.go
  vendor/github.com/davecgh/go-spew/spew/format.go
  vendor/github.com/davecgh/go-spew/spew/spew.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
Labels: testing
